name = "lifevest-telemetry"
main = "src/index.ts"
compatibility_date = "2024-04-06"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./public" }

[[d1_databases]]
binding = "DB"
database_name = "lifevest-db"
database_id = "7e865b2d-fdd5-479c-ab56-4e566605dd53"
preview_database_id = "DB"

[triggers]
crons = ["0 0 * * *"]